title: GIS Team Capabilities
description: Our doors are open!
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
site_url: https://dynamicsiteshub.github.io/capabilities
collections:
  authors:
    output: true